# Generated by Django 5.2.17 on 2026-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(0, 'Staff'), (1, 'Customer'), (2, 'Seller'), (3, 'Superuser')]),
        ),
    ]
